#frontend.enableClientVersionCheck:
#- value: true
#  constraints: {}
#history.persistenceMaxQPS:
#- value: 3000
#  constraints: {}
#frontend.persistenceMaxQPS:
#- value: 3000
#  constraints: {}
#frontend.throttledLogRPS:
#- value: 20
#  constraints: {}
#history.defaultActivityRetryPolicy:
#- value:
#    InitialIntervalInSeconds: 1
#    MaximumIntervalCoefficient: 100.0
#    BackoffCoefficient: 2.0
#    MaximumAttempts: 0
#history.defaultWorkflowRetryPolicy:
#- value:
#    InitialIntervalInSeconds: 1
#    MaximumIntervalCoefficient: 100.0
#    BackoffCoefficient: 2.0
#    MaximumAttempts: 0
#system.secondaryVisibilityWritingMode:
#  - value: "off"
#    constraints: {}
#system.enableReadFromSecondaryVisibility:
#  - value: false
#    constraints: {}
#system.enableParentClosePolicyWorker:
#  - value: true
system.enableEagerWorkflowStart:
  - value: true
frontend.enableUpdateWorkflowExecution:
  - value: true
frontend.enableUpdateWorkflowExecutionAsyncAccepted:
  - value: true
frontend.workerVersioningDataAPIs:
  - value: true
frontend.workerVersioningWorkflowAPIs:
  - value: true
frontend.accessHistoryFraction:
  - value: 1.0

#matching.maxBacklogAgeTarget:
#  - value: 3m
#    constraints:
#      namespace: backlog_aware_t2
#      taskQueueName: tq
#      taskType: Activity

#matching.fairOrdering:
#  - value: true
#    constraints:
#      namespace: default
#      taskQueueName: fair_ordering
#      taskType: Activity

matching.numTaskqueueWritePartitions:
  - value: 2
    constraints:
      namespace: default_t2
#      taskQueueName: <task queue name>
matching.numTaskqueueReadPartitions:
  - value: 2
    constraints:
      namespace: default_t2
#      taskQueueName: <task queue name>